# Generated by Django 4.2.7 on 2025-08-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='youtube_videos',
            field=models.TextField(blank=True),
        ),
    ]
