# Generated by Django 4.2.7 on 2025-08-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_youtube_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='detected_language',
            field=models.CharField(default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='document',
            name='summary_translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('auto', 'Auto-detect')], default='auto', max_length=5),
        ),
    ]
