# Generated by Django 4.2.7 on 2025-08-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quiz',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German')], default='en', max_length=5),
        ),
    ]
